microservice:
  order-service:
    endpoints:
      endpoint:
        uri: http://order-service/order/user/
      endpoint2:
        uri: http://order-service/order/deleteUser/  
  user-service:
    endpoints:
      endpoint:
        uri: http://user-service/user/     
